name: Release webapp to loreal

on:
  workflow_dispatch:

jobs:
  Release-to-loreal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-tags: true
        token: ${{secrets.MT_GITHUB_TOKEN}}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Create new version commit
      id: version_commit
      run: |
        cd webapp
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git pull origin main

        HASH=$(git rev-parse --short HEAD)
        VERSION=$(jq -r '.version' package.json)
        FULL_VERSION="${VERSION}+${HASH}"

        yarn version --no-git-tag-version --new-version "$FULL_VERSION"

        git add package.json
        git commit -m "release($FULL_VERSION): released $FULL_VERSION"

    - name: Create and push git tag
      run: |
        TAG_NAME="release-loreal/v${{ steps.version_commit.outputs.full_version }}"
        git tag -a "$TAG_NAME" -m "Release ${{ steps.version_commit.outputs.full_version }} to loreal" HEAD

        git push origin "$TAG_NAME"

    - name: Push version to Github
      run: git push origin main

